server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.220.128:8848
      discovery:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true  # 支持根据服务名自动路由
      default-filters:
        - AddRequestHeader=key,value
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/car/**
        - id: sellers-service
          uri: lb://sellers-service
          predicates:
            - Path=/api/seller/**
        - id: buyers-service
          uri: lb://buyers-service
          predicates:
            - Path=/api/buyer/**
        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/api/orders/**
        - id: inventories-service
          uri: lb://inventories-service
          predicates:
            - Path=/api/inventories/**


# JWT配置
jwt:
  secret-key: houkaihoukaihoukaihoukaihoukaihoukai  # 密钥（实际生产环境建议使用复杂密钥并加密存储）
  ttl: 7200000  # 令牌有效期（7200000毫秒 = 2小时）
  token-name: token  # 请求头中的令牌键名（如Authorization: token值）

# 白名单，不需要验证直接放行
# 登录，注册，主页
auth:
  exclude-paths:
#
    - /api/car/list
    - /api/seller/login
    - /api/seller/register
    - /**