server:
  port: 8082

spring:
  application:
    name: vehicle-common
  profiles:
    active: dev
  mail:
    username: ${cloud-music.mail.username}
    password: ${cloud-music.mail.password}
    host: ${cloud-music.mail.host}


minio:
  endpoint: ${cloud-music.minio.endpoint}
  access-key: ${cloud-music.minio.access-key}
  secret-key: ${cloud-music.minio.secret-key}
  bucket-name: ${cloud-music.minio.bucket-name}
  base-url: ${cloud-music.minio.base-url}