server:
  port: 8082
spring:
  application:
    name: trade-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vehicle_system
    username: root
    password: 1234

  profiles:
    active: dev

  cloud:
    nacos:
      server-addr: 192.168.220.128 #nacos的配置

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com.hosiky.trade:
      mapper: debug
      service: info
      controller: info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hosiky.trade.controller
