server:
  port: 8085

spring:
  application:
    name: car-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vehicle_system
    username: root
    password: 1234
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.220.128 #nacos的配置
  mail:
    host: smtp.126.com
    port: 587
    username: hosiky@126.com
    password: BFQZiSkWcfz25yWn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

minio:
  endpoint: http://192.168.220.128:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: spring-vehicle
  base-url: http://192.168.220.128:9000/spring-vehicle

  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB



feign:
  okhttp:
    enabled: true # 开启OKHttp功能

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # mapper.xml文件路径
  type-enums-package: com.hosiky.common.entity.Enum
  configuration:
    map-underscore-to-camel-case: true  # 关闭驼峰命名转换（根据实际需求调整）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印SQL日志
  global-config:
    db-config:
      id-type: auto  # 主键自增（根据数据库类型调整）

logging:
  level:
    com.hosiky.car:
      mapper: debug
      service: info
      controller: info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hosiky.car.controller